name: Run Cypress Tests and Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Run Cypress Tests
      run: npm run cy:run

    - name: Merge Mochawesome Reports
      run: npm run mochawesome:merge

    - name: Generate Allure Report
      run: npm run report:generate

    - name: Publish Allure Report
      run: npm run allure:publish
